Style/AsciiComments:
  Enabled: false

Style/Encoding:
  Enabled: false

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 25

AbcSize:
  Enabled: false

AllCops:
  Exclude:
    - 'config.ru'
